In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('movies_data.csv')
df

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
...,...,...,...,...,...,...
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   star_rating     1000 non-null   float64
 1   title           1000 non-null   object
 2   content_rating  833 non-null    object
 3   genre           1000 non-null   object
 4   duration        1000 non-null   int64
 5   actors_list     1000 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 47.0+ KB

In [ ]:
#Filtering Datasets

In [6]:

df[df['star_rating']>9]['title'] #here we are filtering the dataset to get the titles of movies with a star rating greater than 9.

6        Movie 7
7        Movie 8
9       Movie 10
18      Movie 19
23      Movie 24
         ...
967    Movie 968
969    Movie 970
972    Movie 973
976    Movie 977
986    Movie 987
Name: title, Length: 138, dtype: object

In [7]:
df[df['star_rating']<7.5] #here we are filtering the dataset to get the movies with a star rating less than 7.5.

,star_rating,title,content_rating,genre,duration,actors_list
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
5,5.7,Movie 6,PG-13,Adventure,91,"['Actor13', 'Actor4', 'Actor12']"
10,6.7,Movie 11,NaN,Drama,169,"['Actor3', 'Actor6', 'Actor18']"
13,5.3,Movie 14,NC-17,Horror,107,"['Actor16', 'Actor13', 'Actor15']"
14,5.7,Movie 15,PG,Crime,175,"['Actor18', 'Actor20', 'Actor9']"
...,...,...,...,...,...,...
992,7.2,Movie 993,PG,Comedy,158,"['Actor2', 'Actor6', 'Actor16']"
994,6.1,Movie 995,R,Thriller,92,"['Actor20', 'Actor12', 'Actor18']"
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [ ]:
[np.where(df['star_rating']>9)] #here we are filtering the dataset to get the movies with a star rating greater than 9 using np.where.

[(array([  6,   7,   9,  18,  23,  25,  26,  29,  36,  37,  38,  41,  47,
          49,  57,  59,  76,  87,  92,  98, 128, 130, 131, 144, 147, 157,
         158, 167, 173, 175, 181, 195, 200, 210, 224, 229, 232, 245, 246,
         257, 259, 269, 279, 291, 322, 323, 333, 355, 356, 369, 386, 392,
         393, 396, 402, 405, 422, 435, 438, 439, 443, 448, 459, 462, 476,
         479, 496, 499, 501, 504, 508, 509, 512, 517, 521, 526, 532, 536,
         540, 545, 548, 549, 558, 570, 573, 575, 577, 589, 600, 602, 604,
         611, 613, 614, 620, 630, 631, 666, 667, 669, 672, 678, 679, 680,
         683, 687, 697, 698, 701, 705, 710, 736, 753, 755, 784, 786, 809,
         812, 815, 819, 838, 840, 869, 871, 876, 882, 885, 899, 926, 938,
         942, 946, 953, 967, 969, 972, 976, 986]),)]

In [8]:
df.loc[np.where(df['star_rating']>9)] #here we are filtering the dataset to get the movies with a star rating greater than 9 using loc and np.where.

,star_rating,title,content_rating,genre,duration,actors_list
6,9.1,Movie 7,NC-17,Drama,85,"['Actor15', 'Actor18', 'Actor4']"
7,9.7,Movie 8,G,Adventure,150,"['Actor10', 'Actor12', 'Actor7']"
9,9.2,Movie 10,G,Drama,138,"['Actor12', 'Actor6', 'Actor20']"
18,9.7,Movie 19,R,Adventure,167,"['Actor18', 'Actor9', 'Actor11']"
23,9.2,Movie 24,R,Adventure,173,"['Actor16', 'Actor3', 'Actor18']"
...,...,...,...,...,...,...
967,9.4,Movie 968,NaN,Drama,93,"['Actor2', 'Actor3', 'Actor19']"
969,9.5,Movie 970,NaN,Romance,114,"['Actor5', 'Actor11', 'Actor13']"
972,9.5,Movie 973,PG-13,Horror,167,"['Actor10', 'Actor13', 'Actor2']"
976,9.2,Movie 977,G,Crime,97,"['Actor2', 'Actor7', 'Actor1']"
986,9.7,Movie 987,NC-17,Thriller,97,"['Actor11', 'Actor7', 'Actor2']"

In [ ]:
#AND condition()

In [10]:
df[(df['star_rating']>9) & (df['duration']>150)]

,star_rating,title,content_rating,genre,duration,actors_list
18,9.7,Movie 19,R,Adventure,167,"['Actor18', 'Actor9', 'Actor11']"
23,9.2,Movie 24,R,Adventure,173,"['Actor16', 'Actor3', 'Actor18']"
92,9.6,Movie 93,PG,Action,159,"['Actor5', 'Actor8', 'Actor20']"
128,9.8,Movie 129,NaN,Drama,153,"['Actor2', 'Actor6', 'Actor16']"
131,9.1,Movie 132,PG-13,Romance,168,"['Actor16', 'Actor10', 'Actor13']"
144,9.5,Movie 145,PG,Crime,153,"['Actor13', 'Actor8', 'Actor14']"
158,9.7,Movie 159,PG-13,Romance,168,"['Actor9', 'Actor15', 'Actor10']"
167,9.6,Movie 168,PG,Crime,166,"['Actor13', 'Actor18', 'Actor12']"
175,9.5,Movie 176,PG-13,Action,168,"['Actor12', 'Actor7', 'Actor15']"
224,9.7,Movie 225,R,Thriller,162,"['Actor6', 'Actor2', 'Actor8']"
245,9.4,Movie 246,G,Comedy,177,"['Actor16', 'Actor15', 'Actor1']"
323,9.2,Movie 324,R,Drama,152,"['Actor20', 'Actor4', 'Actor11']"
386,9.5,Movie 387,G,Comedy,167,"['Actor19', 'Actor13', 'Actor3']"
396,9.5,Movie 397,NaN,Sci-Fi,156,"['Actor20', 'Actor7', 'Actor15']"
422,9.4,Movie 423,NC-17,Adventure,166,"['Actor5', 'Actor11', 'Actor4']"
443,9.2,Movie 444,NaN,Adventure,173,"['Actor15', 'Actor12', 'Actor3']"
462,9.5,Movie 463,PG,Romance,152,"['Actor14', 'Actor12', 'Actor18']"
509,9.7,Movie 510,R,Crime,164,"['Actor8', 'Actor9', 'Actor18']"
512,9.4,Movie 513,R,Horror,152,"['Actor19', 'Actor5', 'Actor7']"
517,9.1,Movie 518,R,Horror,170,"['Actor13', 'Actor19', 'Actor4']"
532,9.7,Movie 533,G,Thriller,172,"['Actor18', 'Actor9', 'Actor10']"
548,9.4,Movie 549,NC-17,Adventure,180,"['Actor10', 'Actor18', 'Actor12']"
549,9.2,Movie 550,PG-13,Romance,163,"['Actor16', 'Actor19', 'Actor20']"
570,9.3,Movie 571,NC-17,Romance,164,"['Actor11', 'Actor5', 'Actor1']"
577,9.1,Movie 578,G,Action,161,"['Actor19', 'Actor20', 'Actor3']"
589,9.8,Movie 590,G,Horror,176,"['Actor7', 'Actor6', 'Actor13']"
600,9.6,Movie 601,NC-17,Adventure,172,"['Actor4', 'Actor9', 'Actor8']"
602,9.2,Movie 603,PG-13,Horror,166,"['Actor11', 'Actor14', 'Actor4']"
604,9.3,Movie 605,NC-17,Drama,173,"['Actor3', 'Actor12', 'Actor11']"
614,9.1,Movie 615,PG,Adventure,176,"['Actor16', 'Actor11', 'Actor8']"
630,9.2,Movie 631,G,Animation,168,"['Actor8', 'Actor9', 'Actor13']"
666,9.6,Movie 667,PG,Drama,166,"['Actor12', 'Actor1', 'Actor18']"
672,9.6,Movie 673,PG-13,Comedy,165,"['Actor8', 'Actor4', 'Actor10']"
679,9.3,Movie 680,NC-17,Action,154,"['Actor19', 'Actor13', 'Actor7']"
683,9.1,Movie 684,NC-17,Comedy,176,"['Actor17', 'Actor5', 'Actor15']"
786,9.7,Movie 787,NC-17,Sci-Fi,168,"['Actor20', 'Actor5', 'Actor12']"
809,9.1,Movie 810,G,Romance,172,"['Actor11', 'Actor8', 'Actor18']"
871,9.6,Movie 872,R,Animation,177,"['Actor9', 'Actor1', 'Actor15']"
876,9.1,Movie 877,NaN,Animation,157,"['Actor10', 'Actor11', 'Actor3']"
882,9.7,Movie 883,G,Animation,180,"['Actor10', 'Actor14', 'Actor11']"
946,9.1,Movie 947,R,Adventure,157,"['Actor6', 'Actor19', 'Actor5']"
972,9.5,Movie 973,PG-13,Horror,167,"['Actor10', 'Actor13', 'Actor2']"

In [11]:

df[(df['star_rating']<8)&(df['duration']>150)&(df['content_rating']=='R')]

,star_rating,title,content_rating,genre,duration,actors_list
28,7.8,Movie 29,R,Adventure,170,"['Actor2', 'Actor8', 'Actor3']"
53,7.7,Movie 54,R,Adventure,168,"['Actor5', 'Actor18', 'Actor2']"
227,5.3,Movie 228,R,Thriller,166,"['Actor13', 'Actor10', 'Actor9']"
233,6.4,Movie 234,R,Thriller,178,"['Actor18', 'Actor17', 'Actor2']"
304,6.6,Movie 305,R,Romance,154,"['Actor10', 'Actor1', 'Actor16']"
340,6.9,Movie 341,R,Crime,154,"['Actor3', 'Actor2', 'Actor14']"
384,7.1,Movie 385,R,Horror,157,"['Actor20', 'Actor13', 'Actor11']"
406,7.9,Movie 407,R,Adventure,178,"['Actor8', 'Actor12', 'Actor6']"
431,5.5,Movie 432,R,Drama,179,"['Actor18', 'Actor12', 'Actor20']"
472,6.3,Movie 473,R,Drama,171,"['Actor19', 'Actor3', 'Actor16']"
474,5.8,Movie 475,R,Animation,166,"['Actor4', 'Actor8', 'Actor17']"
592,7.9,Movie 593,R,Adventure,163,"['Actor1', 'Actor2', 'Actor4']"
655,7.1,Movie 656,R,Drama,163,"['Actor7', 'Actor11', 'Actor17']"
656,5.4,Movie 657,R,Comedy,178,"['Actor18', 'Actor20', 'Actor1']"
691,5.8,Movie 692,R,Thriller,162,"['Actor9', 'Actor7', 'Actor5']"
740,6.5,Movie 741,R,Action,166,"['Actor7', 'Actor13', 'Actor4']"
758,5.9,Movie 759,R,Comedy,173,"['Actor8', 'Actor9', 'Actor3']"
768,7.3,Movie 769,R,Sci-Fi,176,"['Actor16', 'Actor10', 'Actor1']"
799,5.9,Movie 800,R,Animation,162,"['Actor13', 'Actor16', 'Actor17']"
811,5.0,Movie 812,R,Drama,156,"['Actor1', 'Actor17', 'Actor5']"
831,5.5,Movie 832,R,Crime,159,"['Actor5', 'Actor10', 'Actor1']"
857,7.1,Movie 858,R,Animation,174,"['Actor13', 'Actor11', 'Actor20']"
895,5.9,Movie 896,R,Drama,170,"['Actor11', 'Actor2', 'Actor9']"
971,7.6,Movie 972,R,Romance,168,"['Actor16', 'Actor4', 'Actor18']"

In [ ]:
#OR condition()

In [12]:
df[(df['star_rating']>9) | (df['duration']>200)]

,star_rating,title,content_rating,genre,duration,actors_list
6,9.1,Movie 7,NC-17,Drama,85,"['Actor15', 'Actor18', 'Actor4']"
7,9.7,Movie 8,G,Adventure,150,"['Actor10', 'Actor12', 'Actor7']"
9,9.2,Movie 10,G,Drama,138,"['Actor12', 'Actor6', 'Actor20']"
18,9.7,Movie 19,R,Adventure,167,"['Actor18', 'Actor9', 'Actor11']"
23,9.2,Movie 24,R,Adventure,173,"['Actor16', 'Actor3', 'Actor18']"
...,...,...,...,...,...,...
967,9.4,Movie 968,NaN,Drama,93,"['Actor2', 'Actor3', 'Actor19']"
969,9.5,Movie 970,NaN,Romance,114,"['Actor5', 'Actor11', 'Actor13']"
972,9.5,Movie 973,PG-13,Horror,167,"['Actor10', 'Actor13', 'Actor2']"
976,9.2,Movie 977,G,Crime,97,"['Actor2', 'Actor7', 'Actor1']"
986,9.7,Movie 987,NC-17,Thriller,97,"['Actor11', 'Actor7', 'Actor2']"

In [13]:
df[((df['star_rating']>9) & (df['content_rating']=='R')) |((df['genre']=='Adventure') &(df['duration']>200))]

,star_rating,title,content_rating,genre,duration,actors_list
18,9.7,Movie 19,R,Adventure,167,"['Actor18', 'Actor9', 'Actor11']"
23,9.2,Movie 24,R,Adventure,173,"['Actor16', 'Actor3', 'Actor18']"
37,9.2,Movie 38,R,Comedy,128,"['Actor1', 'Actor13', 'Actor9']"
41,9.6,Movie 42,R,Comedy,88,"['Actor20', 'Actor3', 'Actor8']"
76,9.4,Movie 77,R,Sci-Fi,97,"['Actor15', 'Actor17', 'Actor18']"
210,9.1,Movie 211,R,Romance,82,"['Actor15', 'Actor3', 'Actor11']"
224,9.7,Movie 225,R,Thriller,162,"['Actor6', 'Actor2', 'Actor8']"
246,9.3,Movie 247,R,Drama,107,"['Actor5', 'Actor18', 'Actor17']"
269,9.6,Movie 270,R,Comedy,143,"['Actor17', 'Actor13', 'Actor18']"
279,9.4,Movie 280,R,Adventure,146,"['Actor5', 'Actor10', 'Actor6']"
323,9.2,Movie 324,R,Drama,152,"['Actor20', 'Actor4', 'Actor11']"
392,9.1,Movie 393,R,Drama,132,"['Actor13', 'Actor3', 'Actor18']"
479,9.6,Movie 480,R,Sci-Fi,116,"['Actor10', 'Actor11', 'Actor3']"
499,9.4,Movie 500,R,Action,88,"['Actor7', 'Actor15', 'Actor5']"
509,9.7,Movie 510,R,Crime,164,"['Actor8', 'Actor9', 'Actor18']"
512,9.4,Movie 513,R,Horror,152,"['Actor19', 'Actor5', 'Actor7']"
517,9.1,Movie 518,R,Horror,170,"['Actor13', 'Actor19', 'Actor4']"
545,9.4,Movie 546,R,Adventure,129,"['Actor18', 'Actor13', 'Actor20']"
687,9.2,Movie 688,R,Horror,93,"['Actor17', 'Actor9', 'Actor19']"
755,9.1,Movie 756,R,Adventure,100,"['Actor11', 'Actor8', 'Actor20']"
871,9.6,Movie 872,R,Animation,177,"['Actor9', 'Actor1', 'Actor15']"
885,9.7,Movie 886,R,Adventure,83,"['Actor15', 'Actor4', 'Actor7']"
946,9.1,Movie 947,R,Adventure,157,"['Actor6', 'Actor19', 'Actor5']"
953,9.2,Movie 954,R,Drama,137,"['Actor13', 'Actor11', 'Actor17']"

In [ ]:
# isin function() means checking if a value is in a list of values

In [15]:
list1=['R','PG-13','NOT RATED','PG','UNRATED']

In [ ]:
df[df['content_rating'].isin(list1)] #here we are filtering the dataset to get the movies with a content rating in the list1 using isin function.

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
5,5.7,Movie 6,PG-13,Adventure,91,"['Actor13', 'Actor4', 'Actor12']"
8,8.4,Movie 9,R,Crime,178,"['Actor10', 'Actor3', 'Actor8']"
...,...,...,...,...,...,...
992,7.2,Movie 993,PG,Comedy,158,"['Actor2', 'Actor6', 'Actor16']"
993,7.9,Movie 994,R,Drama,124,"['Actor14', 'Actor1', 'Actor18']"
994,6.1,Movie 995,R,Thriller,92,"['Actor20', 'Actor12', 'Actor18']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [17]:
df.loc[np.where(df['content_rating'].isin(list1))]

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
5,5.7,Movie 6,PG-13,Adventure,91,"['Actor13', 'Actor4', 'Actor12']"
8,8.4,Movie 9,R,Crime,178,"['Actor10', 'Actor3', 'Actor8']"
...,...,...,...,...,...,...
992,7.2,Movie 993,PG,Comedy,158,"['Actor2', 'Actor6', 'Actor16']"
993,7.9,Movie 994,R,Drama,124,"['Actor14', 'Actor1', 'Actor18']"
994,6.1,Movie 995,R,Thriller,92,"['Actor20', 'Actor12', 'Actor18']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [ ]:
# NOT OPERATOR

In [ ]:
df.genre.unique()# means we are getting the unique values of the genre column in the dataset.

array(['Drama', 'Adventure', 'Thriller', 'Comedy', 'Crime', 'Sci-Fi',
       'Horror', 'Animation', 'Action', 'Romance'], dtype=object)

In [ ]:
list1=['R','PG-13']
list2=['Crime','Action','Adventure']
df[~(df['content_rating'].isin(list1) | (df['genre'].isin(list2)))] #here we are filtering the dataset to get the movies with a content rating not in the list1 and genre not in the list2 using NOT operator.

,star_rating,title,content_rating,genre,duration,actors_list
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
6,9.1,Movie 7,NC-17,Drama,85,"['Actor15', 'Actor18', 'Actor4']"
9,9.2,Movie 10,G,Drama,138,"['Actor12', 'Actor6', 'Actor20']"
10,6.7,Movie 11,NaN,Drama,169,"['Actor3', 'Actor6', 'Actor18']"
...,...,...,...,...,...,...
986,9.7,Movie 987,NC-17,Thriller,97,"['Actor11', 'Actor7', 'Actor2']"
989,5.6,Movie 990,NaN,Animation,128,"['Actor6', 'Actor1', 'Actor16']"
991,8.3,Movie 992,G,Comedy,106,"['Actor5', 'Actor9', 'Actor17']"
992,7.2,Movie 993,PG,Comedy,158,"['Actor2', 'Actor6', 'Actor16']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"

In [ ]:
#UNIQUE function() is used to get the unique values of a column in the dataset.

In [20]:
df['genre'].unique() # here we are getting the unique values of the genre column in the dataset using unique function.

array(['Drama', 'Adventure', 'Thriller', 'Comedy', 'Crime', 'Sci-Fi',
       'Horror', 'Animation', 'Action', 'Romance'], dtype=object)

In [22]:
df['genre'].nunique() # here we are getting the number of unique values of the genre column in the dataset using nunique function.]

10

In [ ]:
#nunique() means we are getting the number of unique values of a column in the dataset.

In [23]:
df['genre'].nunique()

10

In [24]:
df['content_rating'].nunique() # here we are getting the number of unique values of the content_rating column in the dataset using nunique function.

5

In [ ]:
# Value_counts() function is used to get the count of unique values of a column in the dataset.

In [25]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
...,...,...,...,...,...,...
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [26]:
df['genre'].value_counts() # here we are getting the count of unique values of the genre column in the dataset using value_counts function.

genre
Drama        109
Animation    108
Sci-Fi       107
Adventure    106
Comedy       106
Crime        102
Thriller      95
Action        92
Romance       88
Horror        87
Name: count, dtype: int64

In [28]:
df[df['genre']=='Action'] #here we are filtering the dataset to get the rows where the genre column has the value 'Action'.

,star_rating,title,content_rating,genre,duration,actors_list
16,7.4,Movie 17,R,Action,94,"['Actor5', 'Actor6', 'Actor14']"
32,7.0,Movie 33,NaN,Action,166,"['Actor4', 'Actor2', 'Actor13']"
39,5.9,Movie 40,PG,Action,154,"['Actor18', 'Actor2', 'Actor11']"
45,7.2,Movie 46,R,Action,138,"['Actor20', 'Actor19', 'Actor4']"
51,7.4,Movie 52,PG-13,Action,91,"['Actor14', 'Actor9', 'Actor2']"
...,...,...,...,...,...,...
935,5.9,Movie 936,NC-17,Action,153,"['Actor16', 'Actor8', 'Actor17']"
944,8.9,Movie 945,NC-17,Action,116,"['Actor16', 'Actor3', 'Actor5']"
950,7.8,Movie 951,PG-13,Action,162,"['Actor9', 'Actor4', 'Actor2']"
979,5.3,Movie 980,NaN,Action,131,"['Actor4', 'Actor7', 'Actor17']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"

In [ ]:
#groupby() means we are grouping the dataset by a column and performing an aggregation function on it.

In [ ]:
df.groupby('genre')

In [ ]:
#getgroup() function is used to get the group of a specific value in the grouped dataset.

In [30]:
import pandas as pd

In [31]:
df.groupby('genre')

In [34]:
df.groupby('genre').get_group('Action')

,star_rating,title,content_rating,genre,duration,actors_list
16,7.4,Movie 17,R,Action,94,"['Actor5', 'Actor6', 'Actor14']"
32,7.0,Movie 33,NaN,Action,166,"['Actor4', 'Actor2', 'Actor13']"
39,5.9,Movie 40,PG,Action,154,"['Actor18', 'Actor2', 'Actor11']"
45,7.2,Movie 46,R,Action,138,"['Actor20', 'Actor19', 'Actor4']"
51,7.4,Movie 52,PG-13,Action,91,"['Actor14', 'Actor9', 'Actor2']"
...,...,...,...,...,...,...
935,5.9,Movie 936,NC-17,Action,153,"['Actor16', 'Actor8', 'Actor17']"
944,8.9,Movie 945,NC-17,Action,116,"['Actor16', 'Actor3', 'Actor5']"
950,7.8,Movie 951,PG-13,Action,162,"['Actor9', 'Actor4', 'Actor2']"
979,5.3,Movie 980,NaN,Action,131,"['Actor4', 'Actor7', 'Actor17']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"

In [35]:
df['genre'].unique()

array(['Drama', 'Adventure', 'Thriller', 'Comedy', 'Crime', 'Sci-Fi',
       'Horror', 'Animation', 'Action', 'Romance'], dtype=object)

In [36]:
df['content_rating'].unique()

array(['R', 'NC-17', 'PG', nan, 'PG-13', 'G'], dtype=object)

In [33]:
df.groupby('genre').get_group('Adventure') #here we are getting the group of the genre column with the value 'Adventure' using get_group function.

,star_rating,title,content_rating,genre,duration,actors_list
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
5,5.7,Movie 6,PG-13,Adventure,91,"['Actor13', 'Actor4', 'Actor12']"
7,9.7,Movie 8,G,Adventure,150,"['Actor10', 'Actor12', 'Actor7']"
18,9.7,Movie 19,R,Adventure,167,"['Actor18', 'Actor9', 'Actor11']"
20,8.7,Movie 21,NC-17,Adventure,160,"['Actor10', 'Actor17', 'Actor7']"
...,...,...,...,...,...,...
954,8.3,Movie 955,R,Adventure,148,"['Actor12', 'Actor14', 'Actor9']"
955,6.6,Movie 956,PG-13,Adventure,112,"['Actor19', 'Actor13', 'Actor15']"
973,8.0,Movie 974,NaN,Adventure,126,"['Actor18', 'Actor11', 'Actor3']"
984,8.9,Movie 985,R,Adventure,143,"['Actor20', 'Actor8', 'Actor3']"
987,7.8,Movie 988,PG-13,Adventure,95,"['Actor9', 'Actor5', 'Actor14']"

In [38]:
df.groupby(['genre','content_rating']).get_group(('Comedy','PG-13'))

,star_rating,title,content_rating,genre,duration,actors_list
212,6.9,Movie 213,PG-13,Comedy,159,"['Actor15', 'Actor12', 'Actor3']"
273,6.4,Movie 274,PG-13,Comedy,171,"['Actor6', 'Actor12', 'Actor17']"
355,9.1,Movie 356,PG-13,Comedy,139,"['Actor2', 'Actor18', 'Actor14']"
368,5.8,Movie 369,PG-13,Comedy,97,"['Actor18', 'Actor16', 'Actor6']"
449,6.2,Movie 450,PG-13,Comedy,86,"['Actor13', 'Actor10', 'Actor8']"
494,9.0,Movie 495,PG-13,Comedy,91,"['Actor8', 'Actor12', 'Actor13']"
507,6.5,Movie 508,PG-13,Comedy,83,"['Actor11', 'Actor8', 'Actor1']"
518,6.6,Movie 519,PG-13,Comedy,100,"['Actor14', 'Actor16', 'Actor11']"
523,6.7,Movie 524,PG-13,Comedy,161,"['Actor3', 'Actor11', 'Actor15']"
645,6.3,Movie 646,PG-13,Comedy,100,"['Actor19', 'Actor9', 'Actor1']"
672,9.6,Movie 673,PG-13,Comedy,165,"['Actor8', 'Actor4', 'Actor10']"
696,5.3,Movie 697,PG-13,Comedy,146,"['Actor13', 'Actor19', 'Actor1']"
734,9.0,Movie 735,PG-13,Comedy,179,"['Actor4', 'Actor20', 'Actor3']"
947,8.2,Movie 948,PG-13,Comedy,113,"['Actor8', 'Actor16', 'Actor6']"

In [ ]:
#statistical functions on groupby

In [40]:
df.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [41]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
...,...,...,...,...,...,...
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [45]:
df[df['genre']=='Action'] #here we are filtering the dataset to get the rows where the genre column has the value 'Action' and then performing the sum function on it.

,star_rating,title,content_rating,genre,duration,actors_list
16,7.4,Movie 17,R,Action,94,"['Actor5', 'Actor6', 'Actor14']"
32,7.0,Movie 33,NaN,Action,166,"['Actor4', 'Actor2', 'Actor13']"
39,5.9,Movie 40,PG,Action,154,"['Actor18', 'Actor2', 'Actor11']"
45,7.2,Movie 46,R,Action,138,"['Actor20', 'Actor19', 'Actor4']"
51,7.4,Movie 52,PG-13,Action,91,"['Actor14', 'Actor9', 'Actor2']"
...,...,...,...,...,...,...
935,5.9,Movie 936,NC-17,Action,153,"['Actor16', 'Actor8', 'Actor17']"
944,8.9,Movie 945,NC-17,Action,116,"['Actor16', 'Actor3', 'Actor5']"
950,7.8,Movie 951,PG-13,Action,162,"['Actor9', 'Actor4', 'Actor2']"
979,5.3,Movie 980,NaN,Action,131,"['Actor4', 'Actor7', 'Actor17']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"

In [ ]:
df[df['genre'] == 'Action'].sum(numeric_only=True) #here we are filtering the dataset to get the rows where the genre column has the value 'Action' and then performing the sum function on it.

star_rating      682.7
duration       12013.0
dtype: float64

In [47]:
df.groupby('genre').sum()

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,682.7,Movie 17Movie 33Movie 40Movie 46Movie 52Movie ...,RPGRPG-13PGNC-17GGPG-13NC-17PG-13RGNC-17PG-13N...,12013,"['Actor5', 'Actor6', 'Actor14']['Actor4', 'Act..."
Adventure,814.2,Movie 2Movie 6Movie 8Movie 19Movie 21Movie 24M...,NC-17PG-13GRNC-17RRPG-13PGNC-17RRNC-17GPGGRGGG...,14094,"['Actor14', 'Actor2', 'Actor1']['Actor13', 'Ac..."
Animation,769.0,Movie 16Movie 31Movie 44Movie 57Movie 72Movie ...,GPGNC-17GGGNC-17RPG-13PG-13NC-17GPG-13GGPGNC-1...,14779,"['Actor12', 'Actor8', 'Actor5']['Actor16', 'Ac..."
Comedy,764.5,Movie 5Movie 20Movie 37Movie 38Movie 42Movie 7...,RGPGRRPGPGGNC-17RPGRPGPG-13NC-17NC-17NC-17GRPG...,13892,"['Actor14', 'Actor11', 'Actor9']['Actor1', 'Ac..."
Crime,735.2,Movie 9Movie 13Movie 15Movie 26Movie 34Movie 4...,RRPGGRNC-17PG-13NC-17GPGNC-17NC-17GPG-13PGPG-1...,13385,"['Actor10', 'Actor3', 'Actor8']['Actor11', 'Ac..."
Drama,793.2,Movie 1Movie 7Movie 10Movie 11Movie 35Movie 39...,RNC-17GPGGPG-13PGPGRRPG-13GPG-13PG-13PGNC-17GP...,13872,"['Actor8', 'Actor5', 'Actor4']['Actor15', 'Act..."
Horror,648.1,Movie 14Movie 23Movie 27Movie 28Movie 56Movie ...,NC-17RRRGGNC-17GGNC-17GPG-13NC-17PGPGPG-13NC-1...,11550,"['Actor16', 'Actor13', 'Actor15']['Actor8', 'A..."
Romance,677.6,Movie 18Movie 58Movie 64Movie 68Movie 69Movie ...,GPGNC-17PG-13RPGRPG-13PG-13PGPGGRNC-17PGGRNC-1...,11348,"['Actor15', 'Actor17', 'Actor9']['Actor6', 'Ac..."
Sci-Fi,777.7,Movie 12Movie 25Movie 41Movie 74Movie 77Movie ...,PGPGNC-17RRPGNC-17PGPGPG-13PGGGGRNC-17PGNC-17G...,14176,"['Actor9', 'Actor18', 'Actor8']['Actor6', 'Act..."
Thriller,684.9,Movie 3Movie 4Movie 22Movie 47Movie 49Movie 55...,PGPGPGNC-17PG-13NC-17GNC-17GNC-17NC-17RRGRRPG-...,12178,"['Actor1', 'Actor18', 'Actor7']['Actor8', 'Act..."

In [ ]:
# groupby can also be used with Aggregate functions like mean, median, min, max, count etc.

In [48]:
df.groupby('genre').agg({'duration':'sum'})

           duration
genre
Action        12013
Adventure     14094
Animation     14779
Comedy        13892
Crime         13385
Drama         13872
Horror        11550
Romance       11348
Sci-Fi        14176
Thriller      12178

In [49]:
df.groupby('genre').agg({'duration':'max'})

           duration
genre
Action          180
Adventure       180
Animation       180
Comedy          179
Crime           180
Drama           180
Horror          180
Romance         180
Sci-Fi          179
Thriller        180

In [50]:
df.groupby('genre').agg({'duration':'min'})

           duration
genre
Action           81
Adventure        80
Animation        80
Comedy           81
Crime            80
Drama            82
Horror           82
Romance          82
Sci-Fi           82
Thriller         80

In [51]:
df.groupby('genre').agg({'duration':'mean'})

             duration
genre
Action     130.576087
Adventure  132.962264
Animation  136.842593
Comedy     131.056604
Crime      131.225490
Drama      127.266055
Horror     132.758621
Romance    128.954545
Sci-Fi     132.485981
Thriller   128.189474

In [52]:
df.groupby('genre').agg({'duration':'count'})

           duration
genre
Action           92
Adventure       106
Animation       108
Comedy          106
Crime           102
Drama           109
Horror           87
Romance          88
Sci-Fi          107
Thriller         95

In [53]:
df.groupby('genre').mean('duration')

           star_rating    duration
genre
Action        7.420652  130.576087
Adventure     7.681132  132.962264
Animation     7.120370  136.842593
Comedy        7.212264  131.056604
Crime         7.207843  131.225490
Drama         7.277064  127.266055
Horror        7.449425  132.758621
Romance       7.700000  128.954545
Sci-Fi        7.268224  132.485981
Thriller      7.209474  128.189474

In [54]:
df.groupby('genre')['duration'].mean().reset_index()

       genre    duration
0     Action  130.576087
1  Adventure  132.962264
2  Animation  136.842593
3     Comedy  131.056604
4      Crime  131.225490
5      Drama  127.266055
6     Horror  132.758621
7    Romance  128.954545
8     Sci-Fi  132.485981
9   Thriller  128.189474

In [55]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
...,...,...,...,...,...,...
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [56]:
df.groupby(['genre','content_rating'])['title'].count()

genre      content_rating
Action     G                 12
           NC-17             22
           PG                13
           PG-13             18
           R                 15
Adventure  G                 19
           NC-17             12
           PG                19
           PG-13             16
           R                 23
Animation  G                 27
           NC-17             20
           PG                16
           PG-13             14
           R                 13
Comedy     G                 15
           NC-17             19
           PG                23
           PG-13             14
           R                 15
Crime      G                 20
           NC-17             21
           PG                19
           PG-13             17
           R                 14
Drama      G                  9
           NC-17             17
           PG                16
           PG-13             19
           R                 26
Horror     G                 17
           NC-17             12
           PG                10
           PG-13             13
           R                 16
Romance    G                 16
           NC-17             15
           PG                12
           PG-13             17
           R                 15
Sci-Fi     G                 17
           NC-17             18
           PG                20
           PG-13             19
           R                 17
Thriller   G                 18
           NC-17             17
           PG                16
           PG-13             12
           R                 13
Name: title, dtype: int64

In [57]:
df.groupby(['genre','content_rating'])['duration'].sum().reset_index().head(20)

        genre content_rating  duration
0      Action              G      1537
1      Action          NC-17      2972
2      Action             PG      1830
3      Action          PG-13      2377
4      Action              R      1770
5   Adventure              G      2485
6   Adventure          NC-17      1684
7   Adventure             PG      2426
8   Adventure          PG-13      2011
9   Adventure              R      3195
10  Animation              G      3879
11  Animation          NC-17      2631
12  Animation             PG      2174
13  Animation          PG-13      1955
14  Animation              R      1806
15     Comedy              G      1978
16     Comedy          NC-17      2571
17     Comedy             PG      3059
18     Comedy          PG-13      1790
19     Comedy              R      1932

In [58]:
df.groupby('content_rating')['duration'].max().reset_index()

  content_rating  duration
0              G       180
1          NC-17       180
2             PG       180
3          PG-13       180
4              R       179

In [59]:
df[(df['content_rating'] == 'PG-13') & (df['duration']==180)]

,star_rating,title,content_rating,genre,duration,actors_list
353,5.2,Movie 354,PG-13,Romance,180,"['Actor17', 'Actor11', 'Actor14']"
460,8.6,Movie 461,PG-13,Action,180,"['Actor8', 'Actor16', 'Actor13']"
675,5.8,Movie 676,PG-13,Crime,180,"['Actor8', 'Actor14', 'Actor9']"
789,7.3,Movie 790,PG-13,Thriller,180,"['Actor12', 'Actor15', 'Actor7']"

In [ ]:
# agg function in groupby

In [63]:
import numpy as np

In [61]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,8.1,Movie 1,R,Drama,111,"['Actor8', 'Actor5', 'Actor4']"
1,8.2,Movie 2,NC-17,Adventure,155,"['Actor14', 'Actor2', 'Actor1']"
2,5.4,Movie 3,PG,Thriller,157,"['Actor1', 'Actor18', 'Actor7']"
3,8.4,Movie 4,NaN,Thriller,133,"['Actor8', 'Actor15', 'Actor9']"
4,8.9,Movie 5,R,Comedy,169,"['Actor14', 'Actor11', 'Actor9']"
...,...,...,...,...,...,...
995,7.4,Movie 996,G,Crime,115,"['Actor2', 'Actor7', 'Actor4']"
996,8.8,Movie 997,NaN,Sci-Fi,143,"['Actor6', 'Actor20', 'Actor2']"
997,5.3,Movie 998,PG-13,Drama,106,"['Actor14', 'Actor9', 'Actor11']"
998,8.0,Movie 999,G,Action,93,"['Actor2', 'Actor18', 'Actor6']"
999,5.8,Movie 1000,R,Sci-Fi,145,"['Actor4', 'Actor3', 'Actor8']"

In [64]:
df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()

C:\Users\DELL\AppData\Local\Temp\ipykernel_3384\3529585014.py:1: FutureWarning: The provided callable <function mean at 0x000001D32779A7A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()
C:\Users\DELL\AppData\Local\Temp\ipykernel_3384\3529585014.py:1: FutureWarning: The provided callable <function median at 0x000001D327904860> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()
C:\Users\DELL\AppData\Local\Temp\ipykernel_3384\3529585014.py:1: FutureWarning: The provided callable <function sum at 0x000001D3277993A0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()
C:\Users\DELL\AppData\Local\Temp\ipykernel_3384\3529585014.py:1: FutureWarning: The provided callable <function max at 0x000001D327799DA0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()
C:\Users\DELL\AppData\Local\Temp\ipykernel_3384\3529585014.py:1: FutureWarning: The provided callable <function min at 0x000001D327799EE0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('content_rating')['star_rating'].agg((np.mean,np.median,np.sum,np.max,np.min)).reset_index()

  content_rating      mean  median     sum  max  min
0              G  7.444706     7.6  1265.6  9.8  5.0
1          NC-17  7.381503     7.5  1277.0  9.7  5.0
2             PG  7.294512     7.3  1196.3  9.8  5.0
3          PG-13  7.332704     7.3  1165.9  9.8  5.0
4              R  7.422156     7.4  1239.5  9.7  5.0

In [ ]:
df

In [66]:

df.groupby('genre').agg({'star_rating':'mean','content_rating':'count'}) #here we will doing  the for  2 colums we are applying the aggregate function.

           star_rating  content_rating
genre
Action        7.420652              80
Adventure     7.681132              89
Animation     7.120370              90
Comedy        7.212264              86
Crime         7.207843              91
Drama         7.277064              87
Horror        7.449425              68
Romance       7.700000              75
Sci-Fi        7.268224              91
Thriller      7.209474              76

In [67]:
df.groupby('genre').aggregate({'star_rating':'mean','content_rating':'count'})

           star_rating  content_rating
genre
Action        7.420652              80
Adventure     7.681132              89
Animation     7.120370              90
Comedy        7.212264              86
Crime         7.207843              91
Drama         7.277064              87
Horror        7.449425              68
Romance       7.700000              75
Sci-Fi        7.268224              91
Thriller      7.209474              76

In [ ]:
# sort in groupby

In [ ]:
df.groupby('genre',sort=True).aggregate({'star_rating':'mean','content_rating':'count'}) #here sort=True means it will sort in the Alphabetical order)

           star_rating  content_rating
genre
Action        7.420652              80
Adventure     7.681132              89
Animation     7.120370              90
Comedy        7.212264              86
Crime         7.207843              91
Drama         7.277064              87
Horror        7.449425              68
Romance       7.700000              75
Sci-Fi        7.268224              91
Thriller      7.209474              76

In [ ]:
df.groupby('genre',sort=False).aggregate({'star_rating':'mean','content_rating':'count'}) # here sort=False means it will give the order of the first appearance on the datase.

           star_rating  content_rating
genre
Drama         7.277064              87
Adventure     7.681132              89
Thriller      7.209474              76
Comedy        7.212264              86
Crime         7.207843              91
Sci-Fi        7.268224              91
Horror        7.449425              68
Animation     7.120370              90
Action        7.420652              80
Romance       7.700000              75

In [ ]:
# ngroups :--> It tells you the number of groups created by groupby()

In [70]:
df.groupby('genre').ngroups

10

In [71]:
df.genre.nunique()

10

In [ ]:
#Size() function is used to get the size of each group in the grouped dataset.

In [72]:
df.groupby('genre').size()

genre
Action        92
Adventure    106
Animation    108
Comedy       106
Crime        102
Drama        109
Horror        87
Romance       88
Sci-Fi       107
Thriller      95
dtype: int64

In [73]:
df.groupby('genre').agg({'duration':'count'})

           duration
genre
Action           92
Adventure       106
Animation       108
Comedy          106
Crime           102
Drama           109
Horror           87
Romance          88
Sci-Fi          107
Thriller         95

In [74]:
df.groupby('genre')['title'].count()

genre
Action        92
Adventure    106
Animation    108
Comedy       106
Crime        102
Drama        109
Horror        87
Romance       88
Sci-Fi       107
Thriller      95
Name: title, dtype: int64

In [75]:
df.genre.value_counts()

genre
Drama        109
Animation    108
Sci-Fi       107
Adventure    106
Comedy       106
Crime        102
Thriller      95
Action        92
Romance       88
Horror        87
Name: count, dtype: int64