In [2]:
import pandas as pd
import numpy as np

In [3]:
#Loc Functions 
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
# we can create custom index also 
df=pd.read_csv('Iris.csv')
# setting any column of df as index 
df.set_index('Id',inplace=True)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# syntax of Loc
df.loc[rows,columns] #Differentiating by comma(,)

In [6]:
#Loc uses actual values of index and columns
df.loc[:,:]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df.loc[1] # we can access through index value

SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 1, dtype: object

In [8]:
df.loc[5]

SepalLengthCm            5.0
SepalWidthCm             3.6
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 5, dtype: object

In [ ]:
# df.loc[5,2] # Throws error, as you need to gie the name of column.
# in the loc fuction we need to mention the column name 
df.loc[5,'SepalWidthCm'] # like this we need to access

np.float64(3.6)

In [10]:
df.loc[[3,5]]

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
3             4.7           3.2            1.3           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
#we can acess multiple roes and columns at time
df.loc[[3,5,50,100]] #it will access the current id of the rows and columns

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
3              4.7           3.2            1.3           0.2      Iris-setosa
5              5.0           3.6            1.4           0.2      Iris-setosa
50             5.0           3.3            1.4           0.2      Iris-setosa
100            5.7           2.8            4.1           1.3  Iris-versicolor

In [18]:
df1=pd.read_csv('Iris.csv')
#setting any column of df as index
df1.set_index('SepalWidthCm',inplace=True)
df1

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
SepalWidthCm
3.5             1            5.1            1.4           0.2     Iris-setosa
3.0             2            4.9            1.4           0.2     Iris-setosa
3.2             3            4.7            1.3           0.2     Iris-setosa
3.1             4            4.6            1.5           0.2     Iris-setosa
3.6             5            5.0            1.4           0.2     Iris-setosa
...           ...            ...            ...           ...             ...
3.0           146            6.7            5.2           2.3  Iris-virginica
2.5           147            6.3            5.0           1.9  Iris-virginica
3.0           148            6.5            5.2           2.0  Iris-virginica
3.4           149            6.2            5.4           2.3  Iris-virginica
3.0           150            5.9            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [19]:
df1.loc[3]

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
3.0             2            4.9            1.4           0.2      Iris-setosa
3.0            13            4.8            1.4           0.1      Iris-setosa
3.0            14            4.3            1.1           0.1      Iris-setosa
3.0            26            5.0            1.6           0.2      Iris-setosa
3.0            39            4.4            1.3           0.2      Iris-setosa
3.0            46            4.8            1.4           0.3      Iris-setosa
3.0            62            5.9            4.2           1.5  Iris-versicolor
3.0            67            5.6            4.5           1.5  Iris-versicolor
3.0            76            6.6            4.4           1.4  Iris-versicolor
3.0            78            6.7            5.0           1.7  Iris-versicolor
3.0            85            5.4            4.5           1.5  Iris-versicolor
3.0            89            5.6            4.1           1.3  Iris-versicolor
3.0            92            6.1            4.6           1.4  Iris-versicolor
3.0            96            5.7            4.2           1.2  Iris-versicolor
3.0           103            7.1            5.9           2.1   Iris-virginica
3.0           105            6.5            5.8           2.2   Iris-virginica
3.0           106            7.6            6.6           2.1   Iris-virginica
3.0           113            6.8            5.5           2.1   Iris-virginica
3.0           117            6.5            5.5           1.8   Iris-virginica
3.0           128            6.1            4.9           1.8   Iris-virginica
3.0           130            7.2            5.8           1.6   Iris-virginica
3.0           136            7.7            6.1           2.3   Iris-virginica
3.0           139            6.0            4.8           1.8   Iris-virginica
3.0           146            6.7            5.2           2.3   Iris-virginica
3.0           148            6.5            5.2           2.0   Iris-virginica
3.0           150            5.9            5.1           1.8   Iris-virginica

In [ ]:
df1.loc[[3,2.5]]

In [22]:
df1.loc[2.5]

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
2.5            70            5.6            3.9           1.1  Iris-versicolor
2.5            73            6.3            4.9           1.5  Iris-versicolor
2.5            90            5.5            4.0           1.3  Iris-versicolor
2.5            99            5.1            3.0           1.1  Iris-versicolor
2.5           107            4.9            4.5           1.7   Iris-virginica
2.5           109            6.7            5.8           1.8   Iris-virginica
2.5           114            5.7            5.0           2.0   Iris-virginica
2.5           147            6.3            5.0           1.9   Iris-virginica

In [ ]:
df1.loc[[2.5],'PetalLengthCm'] #it will access the row with index 2.5 and column PetalLengthCm

In [25]:
df.loc[[3,5],['PetalLengthCm','PetalWidthCm']] #it will access the row with index 3 and 5 and column PetalLengthCm and PetalWidthCm

    PetalLengthCm  PetalWidthCm
Id
3             1.3           0.2
5             1.4           0.2

In [ ]:
df # it will access the row with index 3 and 5 and column PetalLengthCm and PetalWidthCm

In [27]:
df.loc[df['PetalLengthCm']>6] # it will access the row with index 3 and 5 and column PetalLengthCm and PetalWidthCm

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
106            7.6           3.0            6.6           2.1  Iris-virginica
108            7.3           2.9            6.3           1.8  Iris-virginica
110            7.2           3.6            6.1           2.5  Iris-virginica
118            7.7           3.8            6.7           2.2  Iris-virginica
119            7.7           2.6            6.9           2.3  Iris-virginica
123            7.7           2.8            6.7           2.0  Iris-virginica
131            7.4           2.8            6.1           1.9  Iris-virginica
132            7.9           3.8            6.4           2.0  Iris-virginica
136            7.7           3.0            6.1           2.3  Iris-virginica

In [ ]:
df.loc[df['PetalLengthCm']>6,['SepalWidthCm']] # it will access the row with index 3 and 5 and column PetalLengthCm and PetalWidthCm

In [29]:
df.loc[(df['PetalLengthCm']>1) & (df['PetalWidthCm']<8)] # it will access the row with index 3 and 5 and column PetalLengthCm and PetalWidthCm

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
# ILOC Function : it is used to access the rows and columns by their integer position. It is similar to loc function but it uses integer index instead of actual values of index and columns.
# This is number based, not the actual values
#ILOC means index based data selecting method.

In [ ]:
df=pd.read_csv('Iris.csv')
#setting any column of df as index
df.set_index('SepalWidthCm',inplace=True)
df

In [39]:
df1

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
SepalWidthCm
3.5             1            5.1            1.4           0.2     Iris-setosa
3.0             2            4.9            1.4           0.2     Iris-setosa
3.2             3            4.7            1.3           0.2     Iris-setosa
3.1             4            4.6            1.5           0.2     Iris-setosa
3.6             5            5.0            1.4           0.2     Iris-setosa
...           ...            ...            ...           ...             ...
3.0           146            6.7            5.2           2.3  Iris-virginica
2.5           147            6.3            5.0           1.9  Iris-virginica
3.0           148            6.5            5.2           2.0  Iris-virginica
3.4           149            6.2            5.4           2.3  Iris-virginica
3.0           150            5.9            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [37]:
df1.iloc[0] # it will access the first row of the DataFrame

Id                         1
SepalLengthCm            5.1
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 3.5, dtype: object

In [41]:
df1.iloc[5] # it will access the 5th row of the DataFrame

Id                         6
SepalLengthCm            5.4
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Name: 3.9, dtype: object

In [42]:
df.iloc[[0,1]] # it will access the rows with indices 0 and 1

              Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
SepalWidthCm
3.5            1            5.1            1.4           0.2  Iris-setosa
3.0            2            4.9            1.4           0.2  Iris-setosa

In [ ]:
df.iloc[:3]# it will access the first 3 rows of the DataFrame

              Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
SepalWidthCm
3.5            1            5.1            1.4           0.2  Iris-setosa
3.0            2            4.9            1.4           0.2  Iris-setosa
3.2            3            4.7            1.3           0.2  Iris-setosa

In [44]:
df.iloc[lambda x: x.index %2==0]#it will access the rows with even index values of the DataFrame

              Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
4.0           15            5.8            1.2           0.2      Iris-setosa
2.0           61            5.0            3.5           1.0  Iris-versicolor

In [46]:
df.iloc[1:3,0:3] # it will access the rows with index values 1,2,3 of the DataFrame

              Id  SepalLengthCm  PetalLengthCm
SepalWidthCm
3.0            2            4.9            1.4
3.2            3            4.7            1.3

In [47]:
df.columns

Index(['Id', 'SepalLengthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'], dtype='object')

In [48]:
df.iloc[1:5,1:4] # it will access the rows with index values 1,2,3,4 and columns with index values 1,2,3 of the DataFrame

              SepalLengthCm  PetalLengthCm  PetalWidthCm
SepalWidthCm
3.0                     4.9            1.4           0.2
3.2                     4.7            1.3           0.2
3.1                     4.6            1.5           0.2
3.6                     5.0            1.4           0.2

In [49]:
df.iloc[2,2]

np.float64(1.3)

In [50]:
df.iloc[2,2]=100 # modify the value of the cell at row index 2 and column index 2 to 100

In [52]:
df.head(5)

              Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
SepalWidthCm
3.5            1            5.1            1.4           0.2  Iris-setosa
3.0            2            4.9            1.4           0.2  Iris-setosa
3.2            3            4.7          100.0           0.2  Iris-setosa
3.1            4            4.6            1.5           0.2  Iris-setosa
3.6            5            5.0            1.4           0.2  Iris-setosa