In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("Generated_Dataset.csv") 
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [6]:
df.shape

(1000, 8)

In [ ]:
df.head() # it will display the top 5 records

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Emp ID          1000 non-null   int64
 1   First Name      1000 non-null   object
 2   Age in Yrs      950 non-null    float64
 3   Weight in Kgs   922 non-null    float64
 4   Age in Company  1000 non-null   float64
 5   Salary          1000 non-null   int64
 6   City            1000 non-null   object
 7   Designation     1000 non-null   object
dtypes: float64(3), int64(2), object(3)
memory usage: 62.6+ KB

In [ ]:
df.isnull() # This will return a boolean DataFrame indicating the presence of null values

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [11]:
#simple example i have created dataset
import pandas as pd 
import numpy as np
#sample DataFrame with missing values
df1=pd.DataFrame({'A':[1,np.nan,3],'B':[4,5,np.nan]})
#Detecting missing values using isnull()
df1.isnull()

       A      B
0  False  False
1   True  False
2  False   True

In [12]:
#Detecing missing values using isna()
df1.isna()

       A      B
0  False  False
1   True  False
2  False   True

In [ ]:
df.isnull().sum() #it will give me how many null values are present in the columns

Emp ID             0
First Name         0
Age in Yrs        50
Weight in Kgs     78
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [14]:
# We can calculate the % of the nullvalues in the each of the columns
df.isnull().sum() * 100/df.shape[0]

Emp ID            0.0
First Name        0.0
Age in Yrs        5.0
Weight in Kgs     7.8
Age in Company    0.0
Salary            0.0
City              0.0
Designation       0.0
dtype: float64

In [15]:
#We can achive same condition using for loop 
for i,j in zip(df.columns,df.isnull().sum()):
    print(f"Percentage Null Valaue in column {i}:{j*100/df.shape[0]}%",)

Percentage Null Valaue in column Emp ID:0.0%
Percentage Null Valaue in column First Name:0.0%
Percentage Null Valaue in column Age in Yrs:5.0%
Percentage Null Valaue in column Weight in Kgs:7.8%
Percentage Null Valaue in column Age in Company:0.0%
Percentage Null Valaue in column Salary:0.0%
Percentage Null Valaue in column City:0.0%
Percentage Null Valaue in column Designation:0.0%

In [16]:
df.dropna() #deletes the entire rows wherever it finds null values

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [18]:
df.shape

(1000, 8)

In [19]:
# whenever we use the Inplace = True at the time only the dataset is modified
df.dropna(inplace=True)
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [20]:
df= pd.read_csv('Generated_Dataset.csv')
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
# Threshold Parameter in Dropping

In [ ]:
df.isna().sum()

In [23]:
df.dropna(thresh=6,axis=0) # at least 6 columns should have non-null values otherwise frop that row

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
# Subset parameter

In [25]:
df.dropna(subset=['Weight in Kgs'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [26]:
df.dropna(subset=['Weight in Kgs']).isna().sum()

Emp ID             0
First Name         0
Age in Yrs        46
Weight in Kgs      0
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [27]:
df.dropna(subset=['City'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [28]:
df.shape

(1000, 8)

In [30]:
df.dropna(subset=['City','Age in Yrs'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [31]:
df.dropna(subset=['City','Age in Yrs']).isna().sum()

Emp ID             0
First Name         0
Age in Yrs         0
Weight in Kgs     74
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [32]:
df.dropna(subset=['City','Age in Yrs','Weight in Kgs']).isna().sum()

Emp ID            0
First Name        0
Age in Yrs        0
Weight in Kgs     0
Age in Company    0
Salary            0
City              0
Designation       0
dtype: int64

In [ ]:
#Determine if row or column is removed from DataFrame, when we have at least one NA or all NA
#1.'any':if any NA values are present, drop that row or column.
#2.'all':if all values are NA,drop that row or column

In [33]:
df.dropna(subset=['City','Age in Company'],how='all')

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [34]:
df.dropna(subset=['City','Weight in Kgs'],how='any')

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:

# Finding Index of the records where it is null

In [35]:

df.isna()

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
np.where(df.isna()) #we can use the numpy where function to find the index of the records where it is null

(array([ 21,  28,  34,  35,  44,  77,  81,  84,  89,  92,  93,  97, 106,
        107, 120, 126, 129, 129, 148, 156, 165, 181, 187, 192, 193, 204,
        219, 224, 227, 237, 247, 269, 278, 286, 287, 291, 293, 294, 299,
        314, 321, 322, 324, 359, 373, 378, 388, 391, 395, 405, 409, 426,
        426, 435, 442, 448, 466, 474, 496, 512, 514, 522, 530, 532, 534,
        534, 539, 543, 550, 552, 555, 556, 561, 563, 566, 566, 572, 573,
        576, 577, 578, 600, 603, 604, 605, 615, 616, 636, 641, 643, 647,
        684, 688, 701, 717, 720, 744, 745, 749, 755, 758, 768, 793, 797,
        809, 812, 814, 815, 828, 865, 871, 875, 880, 894, 898, 901, 910,
        915, 929, 942, 948, 949, 950, 951, 956, 968, 977, 985]),
 array([3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
        3, 2, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 3,
        2, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 3, 3, 2,
        2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 3,
        2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 3, 2]))

In [ ]:

df.columns # it will give me the list of the columns present in the dataset

Index(['Emp ID', 'First Name', 'Age in Yrs', 'Weight in Kgs', 'Age in Company',
       'Salary', 'City', 'Designation'],
      dtype='object')

In [ ]:
df.loc[977] # we can use the loc to find the record where it is null

Emp ID                83970
First Name        Priya_978
Age in Yrs            29.87
Weight in Kgs           NaN
Age in Company         14.8
Salary               139797
City              Hyderabad
Designation         Manager
Name: 977, dtype: object

In [39]:

df.loc[21,'Weight in Kgs'] #here we are using the loc to find the record where it is null and also we can use the column name to find the specific column value

np.float64(nan)

In [41]:
df.loc[21,'Weight in Kgs'] = 30 # here we are using the loc to find the record where it is null values  and also we can set the new value.

In [42]:
df.loc[21,'Weight in Kgs']

np.float64(30.0)

In [ ]:
np.where(df['Age in Company'].isnull()) # Find the index of records where 'Age in Company' is null

(array([], dtype=int64),)

In [ ]:
# Filter dataset only for Null Values

In [ ]:
df[df['Weight in Kgs'].isna()] # Filter dataset only for Null Values in 'Weight in Kgs' column

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
28,53132,Anika_029,42.20,NaN,9.99,148151,Hyderabad,Senior Manager
34,98956,Anika_035,35.07,NaN,9.06,86528,Surat,Executive
77,21305,Anika_078,23.81,NaN,2.05,56838,Bangalore,Associate
81,99731,Priya_082,47.34,NaN,14.27,106166,Mumbai,Senior Manager
84,49194,Ishaan_085,26.00,NaN,1.35,115630,Mumbai,Manager
...,...,...,...,...,...,...,...,...
942,95256,Anika_943,34.84,NaN,6.23,78448,Delhi,Senior Manager
949,73893,Ishaan_950,45.69,NaN,10.81,82802,Jaipur,Senior Manager
951,53795,Vivaan_952,24.25,NaN,23.25,56418,Hyderabad,Executive
968,75042,Aarav_969,42.31,NaN,15.10,70183,Bangalore,Senior Manager
977,83970,Priya_978,29.87,NaN,14.80,139797,Hyderabad,Manager

In [ ]:
# Fixing Null Values

In [46]:
# creating a small dummy DataFrame with null values
import pandas as pd
import numpy as np

# Creating a small dummy DataFrame with null values
np.random.seed(0)  # For reproducible output
data = {
    'A': [1, 2, np.nan, 4, 5, np.nan, 7, 8, 9, 10],
    'B': [np.nan, 1, 2, 3, 4, 5, np.nan, 7, 8, 9],
    'C': [2, 3, 4, np.nan, np.nan, np.nan, 7, 8, 9, 10],
    'D': ['x', np.nan, 'y', 'x', 'y', 'x', np.nan, 'y', 'x', 'y']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
df

Original DataFrame:

      A    B     C    D
0   1.0  NaN   2.0    x
1   2.0  1.0   3.0  NaN
2   NaN  2.0   4.0    y
3   4.0  3.0   NaN    x
4   5.0  4.0   NaN    y
5   NaN  5.0   NaN    x
6   7.0  NaN   7.0  NaN
7   8.0  7.0   8.0    y
8   9.0  8.0   9.0    x
9  10.0  9.0  10.0    y

In [48]:
# Dropping all values of Null in df
df.dropna()  # Drops rows with any null values

      A    B     C  D
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [49]:
df.dropna(how='any')  # Drops rows where all values are null

      A    B     C  D
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [50]:
# Drop columns with any null values
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:

# Fill with a specific value
df.fillna(0)

      A    B     C  D
0   1.0  0.0   2.0  x
1   2.0  1.0   3.0  0
2   0.0  2.0   4.0  y
3   4.0  3.0   0.0  x
4   5.0  4.0   0.0  y
5   0.0  5.0   0.0  x
6   7.0  0.0   7.0  0
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [ ]:
# Fill with mean for numeric columns
df.fillna(df.mean())

In [53]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [54]:
df

      A    B     C    D
0   1.0  NaN   2.0    x
1   2.0  1.0   3.0  NaN
2   NaN  2.0   4.0    y
3   4.0  3.0   NaN    x
4   5.0  4.0   NaN    y
5   NaN  5.0   NaN    x
6   7.0  NaN   7.0  NaN
7   8.0  7.0   8.0    y
8   9.0  8.0   9.0    x
9  10.0  9.0  10.0    y

In [55]:

# Correctly fill NaN values in columns 'A' and 'C' with 0
df[['A', 'C']] = df[['A', 'C']].fillna(0)

# Fill NaN values in column 'B' with its own mean
df['B'] = df['B'].fillna(df['B'].mean())

# Fill NaN values in column 'D' with its mode
# This assumes df['D'].mode()[0] does not result in an empty series; otherwise, you should handle that case.
df['D'] = df['D'].fillna(df['D'].mode()[0])

df

      A      B     C  D
0   1.0  4.875   2.0  x
1   2.0  1.000   3.0  x
2   0.0  2.000   4.0  y
3   4.0  3.000   0.0  x
4   5.0  4.000   0.0  y
5   0.0  5.000   0.0  x
6   7.0  4.875   7.0  x
7   8.0  7.000   8.0  y
8   9.0  8.000   9.0  x
9  10.0  9.000  10.0  y

In [56]:
# Fill categorical data with the mode
df.fillna(df['D'].mode()[0])

      A      B     C  D
0   1.0  4.875   2.0  x
1   2.0  1.000   3.0  x
2   0.0  2.000   4.0  y
3   4.0  3.000   0.0  x
4   5.0  4.000   0.0  y
5   0.0  5.000   0.0  x
6   7.0  4.875   7.0  x
7   8.0  7.000   8.0  y
8   9.0  8.000   9.0  x
9  10.0  9.000  10.0  y