In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

In [2]:
import numpy as np
print(np.__version__)

2.2.6

In [ ]:
#creating a dataframe using dictionary in pandas

data = {'column A':[3,4,5,6],
        'column B':[5,6,7,8] }
df = pd.DataFrame(data)
df 
#
#

   column A  column B
0         3         5
1         4         6
2         5         7
3         6         8

In [9]:
# creating a dataframe using list of dictionaries
data = [
    {'column1': 1, 'column2': 'A','column3':'Balaji'},  # Row 1
    {'column1': 2, 'column2': 'B'},  # Row 2
    {'column1': 3, 'column2': 'C'}   # Row 3
]
df = pd.DataFrame(data)
df

   column1 column2 column3
0        1       A  Balaji
1        2       B     NaN
2        3       C     NaN

In [10]:
type(pd.Series([1,2,3]))

pandas.core.series.Series

In [12]:
data ={
    'column':pd.Series([1,2,3]),
    'column':pd.Series(['A','B'])
}
df=pd.DataFrame(data)
df

  column
0      A
1      B

In [13]:

data = [
    [1,'A'],
    [2,'B'],
    [3,'C']
]
columns = ['balaji1','balaji2']
df=pd.DataFrame(data, columns=columns)
df

   balaji1 balaji2
0        1       A
1        2       B
2        3       C

In [14]:
df.dtypes

balaji1     int64
balaji2    object
dtype: object

In [15]:
df = pd.DataFrame({'float':[1.0],
                   'int':[1],
                   'datetime':[pd.Timestamp('20240223')],
                   'string':['Balaji']})
df

   float  int   datetime  string
0    1.0    1 2024-02-23  Balaji

In [16]:
df.dtypes

float              float64
int                  int64
datetime    datetime64[ns]
string              object
dtype: object

In [18]:
#Enforecing datatypes while creating 
# creating using Dictionaries
data = {'column A':['1',4,5,6],
        'column B':[5,8,9,0]}
df = pd.DataFrame(data=data,dtype=np.int8)
df

   column A  column B
0         1         5
1         4         8
2         5         9
3         6         0

In [19]:
df.dtypes

column A    int8
column B    int8
dtype: object

In [21]:
np.array(df['column B'])

array([5, 8, 9, 0], dtype=int8)

In [22]:
array = np.array(df['column A'])
array = array+2
array

array([3, 6, 7, 8], dtype=int8)

In [23]:
#creating using Arrays.
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),
                  columns=['a','b','c'])
df2

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [24]:
#creating empty DataFrame
empty_df=pd.DataFrame()
empty_df

Empty DataFrame
Columns: []
Index: []

In [26]:
# Add the values from the array to a new column named 'A' in the empty DataFrame
empty_df['A'] = array

# Display the updated DataFrame
empty_df

   A
0  3
1  6
2  7
3  8

In [29]:
Matrix = np.array([[3,4,5],
                  [6,7,8],
                  [9,0,1]])
print(Matrix)
print("************")

[[3 4 5]
 [6 7 8]
 [9 0 1]]
************

In [30]:
df=pd.DataFrame(Matrix)
df

   0  1  2
0  3  4  5
1  6  7  8
2  9  0  1

In [31]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [33]:
df=pd.DataFrame(Matrix,columns=list('ABC'))
df

   A  B  C
0  3  4  5
1  6  7  8
2  9  0  1

In [34]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [35]:
list(df.columns)

['A', 'B', 'C']

In [37]:
#How to create a Custom index as wll

df = pd.DataFrame([[1,2],[4,5],[7,8]],
                  # Set custom row index labels
                  index=['cobra','viper','sidewinder'],
                  # Set column names
                  columns=['max_speed','shield'])

# Display the DataFrame
df

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [38]:
df.columns

Index(['max_speed', 'shield'], dtype='object')

In [ ]:
#number of rows and columns.
df.shape
#means (3,2)
# 3 → Number of rows.
# 2 → Number of columns

(3, 2)

In [41]:
#Manipulating Data 

df=pd.DataFrame(Matrix,columns=list('ABC'))
df

   A  B  C
0  3  4  5
1  6  7  8
2  9  0  1

In [43]:
#now we can create one more column in the existing DataFrame
df['D']=[3,4,5] 
df

   A  B  C  D
0  3  4  5  3
1  6  7  8  4
2  9  0  1  5

In [44]:
df['D']=[0,0,1]
df['e']=100
df

   A  B  C  D    e
0  3  4  5  0  100
1  6  7  8  0  100
2  9  0  1  1  100

In [46]:

"""Remember: np.random.randint(low, high, size) 
means generate size random integers from low (inclusive) to high (exclusive)."""
df['F'] = np.random.randint(1,10,3)
df

   A  B  C  D    e  F
0  3  4  5  0  100  4
1  6  7  8  0  100  6
2  9  0  1  1  100  9

In [ ]:
#in dataframe we add what were we can string also
df['G'] = list('str')
df

   A  B  C  D    e  F  G
0  3  4  5  0  100  4  s
1  6  7  8  0  100  6  t
2  9  0  1  1  100  9  r

In [48]:
#in dataframe we add what were we can string also
df['A']=["Balaji","Amazing","Teacher"]
df

         A  B  C  D    e  F  G
0   Balaji  4  5  0  100  4  s
1  Amazing  7  8  0  100  6  t
2  Teacher  0  1  1  100  9  r

In [50]:
#in dataframe we can also add what were we can add list of list also

df['B']=[["Balaji","is"],["an","Amazing"],["Teacher"]]
df

         A              B  C  D    e  F  G
0   Balaji   [Balaji, is]  5  0  100  4  s
1  Amazing  [an, Amazing]  8  0  100  6  t
2  Teacher      [Teacher]  1  1  100  9  r

In [52]:
df.dtypes

A    object
B    object
C     int64
D     int64
e     int64
F     int32
G    object
dtype: object