sorting  Dataframes

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Iris.csv') #loading the dataset or reading the dataset
df

In [ ]:
#sorting in place
df.sort_index(inplace=True)
print("\nDataFrame after sorting by index in place:")
print(df)

In [ ]:
df.sort_index(axis=0)

In [8]:
df.sort_index(axis=0,ascending=False) #it will sort in the descending order

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
149,150,5.9,3.0,5.1,1.8,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
...,...,...,...,...,...,...
4,5,5.0,3.6,1.4,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
0,1,5.1,3.5,1.4,0.2,Iris-setosa

In [9]:
#setting any column of df as index
df1=df.set_index('SepalWidthCm')
df1

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
SepalWidthCm
3.5             1            5.1            1.4           0.2     Iris-setosa
3.0             2            4.9            1.4           0.2     Iris-setosa
3.2             3            4.7            1.3           0.2     Iris-setosa
3.1             4            4.6            1.5           0.2     Iris-setosa
3.6             5            5.0            1.4           0.2     Iris-setosa
...           ...            ...            ...           ...             ...
3.0           146            6.7            5.2           2.3  Iris-virginica
2.5           147            6.3            5.0           1.9  Iris-virginica
3.0           148            6.5            5.2           2.0  Iris-virginica
3.4           149            6.2            5.4           2.3  Iris-virginica
3.0           150            5.9            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df1.sort_index()#it will sort everything from smallest to largest

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
2.0            61            5.0            3.5           1.0  Iris-versicolor
2.2            63            6.0            4.0           1.0  Iris-versicolor
2.2           120            6.0            5.0           1.5   Iris-virginica
2.2            69            6.2            4.5           1.5  Iris-versicolor
2.3            88            6.3            4.4           1.3  Iris-versicolor
...           ...            ...            ...           ...              ...
3.9             6            5.4            1.7           0.4      Iris-setosa
4.0            15            5.8            1.2           0.2      Iris-setosa
4.1            33            5.2            1.5           0.1      Iris-setosa
4.2            34            5.5            1.4           0.2      Iris-setosa
4.4            16            5.7            1.5           0.4      Iris-setosa

[150 rows x 5 columns]

In [ ]:
df

In [ ]:
df.sort_index(axis=1) #sorting the columns of the dataframe

In [13]:
#creating a Dataframe with unsorted column names
df = pd.DataFrame([[2,1,4],[5,3,6]],columns=['B','A','C'])
print("Original Dataframe:")
df

Original Dataframe:

   B  A  C
0  2  1  4
1  5  3  6

In [14]:
#sorting the DataFrame by its column lables
sorted_df=df.sort_index(axis=1)
print("\nDataFrame after sorting columns by name:")
sorted_df

DataFrame after sorting columns by name:

   A  B  C
0  1  2  4
1  3  5  6

In [16]:
#creating a MultiIndex DataFrame
index = pd.MultiIndex.from_tuples([('a',1),('b',2),('a',2),('b',1)])
df_multi=pd.DataFrame({'A':[1,2,3,4]},index=index)
print("original Multiplex DataFrame:")
df_multi

original Multiplex DataFrame:

     A
a 1  1
b 2  2
a 2  3
b 1  4

In [17]:
#sorting by the first level of the index
sorted_Multi = df_multi.sort_index(level=0)
print("\nMultiIndex DataFrame after sorting by the first level of index:")
sorted_Multi

MultiIndex DataFrame after sorting by the first level of index:

     A
a 1  1
  2  3
b 1  4
  2  2

In [18]:
#sorting by the first level of the index
sorted_Multi_level2 = df_multi.sort_index(level=1)
print("\nMultiIndex DataFrame after sorting by the first level of index:")
sorted_Multi_level2

MultiIndex DataFrame after sorting by the first level of index:

     A
a 1  1
b 1  4
a 2  3
b 2  2

In [23]:
df=pd.read_csv("Iris.csv")
df.shape

(150, 6)

In [22]:
df.T #Transpose of the Dtaframe.(rows becomes columns & columns into rows)

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
Id,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [25]:
(df.T).sort_index(axis=0,ascending=False) # Transpose the DataFrame and sort by the new index (which was originally the columns) in descending order

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
Id,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150

In [26]:
df=pd.read_csv("Iris.csv")
df.set_index('SepalWidthCm',inplace=True)
df.sort_index(inplace=True)
df

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
2.0            61            5.0            3.5           1.0  Iris-versicolor
2.2            63            6.0            4.0           1.0  Iris-versicolor
2.2           120            6.0            5.0           1.5   Iris-virginica
2.2            69            6.2            4.5           1.5  Iris-versicolor
2.3            88            6.3            4.4           1.3  Iris-versicolor
...           ...            ...            ...           ...              ...
3.9             6            5.4            1.7           0.4      Iris-setosa
4.0            15            5.8            1.2           0.2      Iris-setosa
4.1            33            5.2            1.5           0.1      Iris-setosa
4.2            34            5.5            1.4           0.2      Iris-setosa
4.4            16            5.7            1.5           0.4      Iris-setosa

[150 rows x 5 columns]

In [27]:
#setting up default index columns
df.reset_index(inplace=True)
df

,SepalWidthCm,Id,SepalLengthCm,PetalLengthCm,PetalWidthCm,Species
0,2.0,61,5.0,3.5,1.0,Iris-versicolor
1,2.2,63,6.0,4.0,1.0,Iris-versicolor
2,2.2,120,6.0,5.0,1.5,Iris-virginica
3,2.2,69,6.2,4.5,1.5,Iris-versicolor
4,2.3,88,6.3,4.4,1.3,Iris-versicolor
...,...,...,...,...,...,...
145,3.9,6,5.4,1.7,0.4,Iris-setosa
146,4.0,15,5.8,1.2,0.2,Iris-setosa
147,4.1,33,5.2,1.5,0.1,Iris-setosa
148,4.2,34,5.5,1.4,0.2,Iris-setosa
149,4.4,16,5.7,1.5,0.4,Iris-setosa

#sorting by column Values

In [ ]:
df=pd.read_csv('Iris.csv')
df

In [29]:
df.sort_values('SepalLengthCm',ascending=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [30]:
df.sort_values(['PetalLengthCm','PetalWidthCm'],ascending=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
22,23,4.6,3.6,1.0,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
...,...,...,...,...,...,...
131,132,7.9,3.8,6.4,2.0,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica

In [31]:
import pandas as pd

#Example DataFrame
data = {
    'PetalLengthCm':[1.4,1.3,1.5,1.4],
    'PetalWidthCm':[0.2,0.3,0.2,0.3],
    'Species':['setosa','setosa','setosa','setosa']    
}
df=pd.DataFrame(data)
df

   PetalLengthCm  PetalWidthCm Species
0            1.4           0.2  setosa
1            1.3           0.3  setosa
2            1.5           0.2  setosa
3            1.4           0.3  setosa

In [33]:
#sorting by 'PetalLengthCm' primarily then by 'PetalWidthCm'
sorted_df = df.sort_values(['PetalLengthCm','PetalWidthCm'],ascending=True)
sorted_df

   PetalLengthCm  PetalWidthCm Species
1            1.3           0.3  setosa
0            1.4           0.2  setosa
3            1.4           0.3  setosa
2            1.5           0.2  setosa

In [34]:
df.sort_values(['PetalLengthCm','PetalWidthCm'],ascending=[True,False])

   PetalLengthCm  PetalWidthCm Species
1            1.3           0.3  setosa
3            1.4           0.3  setosa
0            1.4           0.2  setosa
2            1.5           0.2  setosa

In [35]:
df.sort_values('Species',ascending=False)

   PetalLengthCm  PetalWidthCm Species
0            1.4           0.2  setosa
1            1.3           0.3  setosa
2            1.5           0.2  setosa
3            1.4           0.3  setosa

#Rearrange order of Columns

In [37]:
import pandas as pd
#Example DataFrame
df=pd.DataFrame({
    'B':[1,2,3],
    'A':[4,5,6],
    'C':[7,8,9]
})
print("original DataFrame:")
df

original DataFrame:

   B  A  C
0  1  4  7
1  2  5  8
2  3  6  9

In [38]:
#specifying the new order of columns
new_order =['A','B','C']

In [39]:
#Rearrange the columns
df_recorded = df[new_order]
print("DataFrame after rearranging columns:")
print(df_recorded)

DataFrame after rearranging columns:
   A  B  C
0  4  1  7
1  5  2  8
2  6  3  9

In [ ]:
df_recorded = df.reindex(['A','B','C'],axis=1)
df_recorded

In [40]:
#Alphabetically
df_sorted = df[sorted(df.columns)]

#Custom sort (e.g.,reverse alphabetical order)
df_custom_sorted = df[sorted(df.columns,reverse=True)]
df_custom_sorted

   C  B  A
0  7  1  4
1  8  2  5
2  9  3  6

In [43]:
df_reordered = df.loc[:,['A','B','C']]
df_recorded

   A  B  C
0  4  1  7
1  5  2  8
2  6  3  9

In [45]:
#Assuming you know the position of the columns you want to reorder
df_recorded = df.iloc[:,[1,0,2]] #Here,1,0,2 represents the new order of column indices
df_recorded

   A  B  C
0  4  1  7
1  5  2  8
2  6  3  9